services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./static/realizace:/app/data/uploads
      - ./prisma:/app/data
    environment:
      NODE_ENV: production
      DATABASE_URL: 'file:/app/data/dev.db'
      UPLOAD_DIR: /app/data/uploads
      BODY_SIZE_LIMIT: 50000000  
