services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./static/realizace:/app/data/uploads
      - ./prisma/dev.db:/app/data/dev.db
    environment:
      NODE_ENV: production
      DATABASE_URL: 'file:///app/data/dev.db'
      UPLOAD_DIR: /app/data/uploads
